# This is the main pipelien which covers all the stages
# The tasks are stored in pipelines/steps.yml
pool:  
  name: Default 

trigger: none 

stages:
  - stage: Dev
    displayName: 'Deploying to Development environment'
    jobs:
      - template: pipelines/steps.yml
        parameters:
          environment: Dev
          hNumber: '123456'
          azureSubscription: 'e078bf8e-61c1-4cd1-a00f-12e22979d32e'
          classicConnection: '6880164a-cb81-4712-bf53-ac4bb12dfcaf'
          WorkspaceName: 'H123456-dev' # Enter the Azure Sentinel Workspace name
          SubscriptionId: 'b00ab83e-b693-4303-b5ad-8790d8c81df4'
          ResourceGroupName: 'H123456-rg'
          ResourceGroupLocation: 'eastus'
          EnableSentinel: true
          analyticsRulesFile: SettingFiles/AlertRules.json # leave empty if you dont want to configure Analytic rules
          huntingRulesFile: SettingFiles/HuntingRules.json # leave empty if you dont want to configure Hunting rules
          PlaybooksFolder: Playbooks/ # leave empty if you dont want to configure Playbooks
          ConnectorsFile: SettingFiles/DataConnectors.json # leave empty if you dont want to configure Connectors
          WorkbooksFolder: #Workbooks/
          WorkbookSourceId: '' # leave empty if you dont want to configure Workbook

  - stage: Staging
    displayName: 'Deploying to Acceptance environment'
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/release'))
    dependsOn: Dev    # this stage runs after Dev
    jobs:
      - template: pipelines/steps.yml
        parameters:
          environment: Staging
          hNumber: '123456'
          azureSubscription: 'e078bf8e-61c1-4cd1-a00f-12e22979d32e'
          WorkspaceName: 'H123456-staging' # Enter the Azure Sentinel Workspace name
          SubscriptionId: 'b00ab83e-b693-4303-b5ad-8790d8c81df4'
          ResourceGroupName: 'H123456-rg'
          ResourceGroupLocation: 'eastus'
          EnableSentinel: true
          analyticsRulesFile: SettingFiles/AlertRules.json # leave empty if you dont want to configure Analytic rules
          huntingRulesFile: SettingFiles/HuntingRules.json # leave empty if you dont want to configure Hunting rules
          PlaybooksFolder: Playbooks/ # leave empty if you dont want to configure Playbooks
          ConnectorsFile: SettingFiles/DataConnectors.json # leave empty if you dont want to configure Connectors
          WorkbooksFolder: #Workbooks/
          WorkbookSourceId: '' # leave empty if you dont want to configure Workbook

  - stage: Production
    displayName: 'Deploying to Production environment'
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    dependsOn: Dev    # this stage runs after Dev
    jobs:
      - template: pipelines/steps.yml
        parameters:
          environment: Production
          hNumber: '123456'
          azureSubscription: 'e078bf8e-61c1-4cd1-a00f-12e22979d32e'
          WorkspaceName: 'H123456-prod'  # Enter the Azure Sentinel Workspace name
          SubscriptionId: 'b00ab83e-b693-4303-b5ad-8790d8c81df4'
          ResourceGroupName: 'H123456-rg'
          ResourceGroupLocation: 'eastus'
          EnableSentinel: true
          analyticsRulesFile: SettingFiles/AlertRules.json # leave empty if you dont want to configure Analytic rules
          huntingRulesFile: SettingFiles/HuntingRules.json # leave empty if you dont want to configure Hunting rules
          PlaybooksFolder: Playbooks/ # leave empty if you dont want to configure Playbooks
          ConnectorsFile: SettingFiles/DataConnectors.json # leave empty if you dont want to configure Connectors
          WorkbooksFolder: #Workbooks/
          WorkbookSourceId: '' # leave empty if you dont want to configure Workbook
